import api from "@/lib/axios";
import { isAxiosError } from "axios";
import { usersResponseSchema } from "../types";

export async function getConfirmedUsers({ page, perPage }: { page: number, perPage: number }) {
    try {
        const url = `/auth/admin/users?page=${page}&perPage=${perPage}`;
        const { data } = await api.get(url);

        const response = usersResponseSchema.safeParse(data);
        if (response.success) {
            console.log("‚úÖ Respuesta exitosa de la API:", response.data);
            return response.data;
        }

        console.error("Schema Validation failed:", response.error);
    } catch (error) {
        console.error("‚ùå Error en la solicitud:", error);

        if (isAxiosError(error)) {
            console.error("üîç Error de Axios detectado:");
            console.error("‚û°Ô∏è C√≥digo de estado:", error.response?.status);
            console.error("‚û°Ô∏è Mensaje de error:", error.response?.data?.error || error.message);
            console.error("‚û°Ô∏è Respuesta completa:", error.response?.data);
            throw new Error(error.response?.data?.message || "Ocurri√≥ un error en la API");
        } else {
            console.error("‚ö†Ô∏è Error desconocido:", error);
            throw new Error("Error inesperado. Intenta nuevamente.");
        }
    }
}


export async function getUnconfirmedUsers() {

}

export async function getUserById() {

}

export async function getUser() {
    try {
        const url = `/auth/user`;
        const response = await api.get(url);
        //console.log(response.data)

        return response.data;
    } catch (error) {
        console.error("‚ùå Error en la solicitud:", error);

        if (isAxiosError(error)) {
            console.error("üîç Error de Axios detectado:");
            console.error("‚û°Ô∏è C√≥digo de estado:", error.response?.status);
            console.error("‚û°Ô∏è Mensaje de error:", error.response?.data?.error || error.message);
            console.error("‚û°Ô∏è Respuesta completa:", error.response?.data);

            // Lanzamos un error m√°s detallado para que pueda ser manejado correctamente
            throw new Error(error.response?.data?.message || "Ocurri√≥ un error en la API");
        } else {
            console.error("‚ö†Ô∏è Error desconocido:", error);
            throw new Error("Error inesperado. Intenta nuevamente.");
        }
    }
}